# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recept_name', models.CharField(max_length=200)),
                ('cals', models.IntegerField()),
                ('ingredienten', models.CharField(max_length=500)),
                ('b_tijd', models.CharField(max_length=20)),
            ],
        ),
    ]
